// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: company.proto

#include "company.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR company::company(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.address_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.open_date_)*/nullptr
  , /*decltype(_impl_.create_time_)*/nullptr
  , /*decltype(_impl_.update_time_)*/nullptr
  , /*decltype(_impl_.id_)*/uint64_t{0u}
  , /*decltype(_impl_.last_year_income_)*/0
  , /*decltype(_impl_.employee_amount_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct companyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR companyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~companyDefaultTypeInternal() {}
  union {
    company _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 companyDefaultTypeInternal _company_default_instance_;
static ::_pb::Metadata file_level_metadata_company_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_company_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_company_2eproto = nullptr;

const uint32_t TableStruct_company_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::company, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::company, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::company, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::company, _impl_.employee_amount_),
  PROTOBUF_FIELD_OFFSET(::company, _impl_.address_),
  PROTOBUF_FIELD_OFFSET(::company, _impl_.open_date_),
  PROTOBUF_FIELD_OFFSET(::company, _impl_.last_year_income_),
  PROTOBUF_FIELD_OFFSET(::company, _impl_.create_time_),
  PROTOBUF_FIELD_OFFSET(::company, _impl_.update_time_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::company)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_company_default_instance_._instance,
};

const char descriptor_table_protodef_company_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rcompany.proto\032\037google/protobuf/timesta"
  "mp.proto\"\370\001\n\007company\022\n\n\002id\030\001 \001(\004\022\014\n\004name"
  "\030\002 \001(\t\022\027\n\017employee_amount\030\003 \001(\r\022\017\n\007addre"
  "ss\030\004 \001(\t\022-\n\topen_date\030\005 \001(\0132\032.google.pro"
  "tobuf.Timestamp\022\030\n\020last_year_income\030\006 \001("
  "\001\022/\n\013create_time\030\007 \001(\0132\032.google.protobuf"
  ".Timestamp\022/\n\013update_time\030\010 \001(\0132\032.google"
  ".protobuf.Timestampb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_company_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_company_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_company_2eproto = {
    false, false, 307, descriptor_table_protodef_company_2eproto,
    "company.proto",
    &descriptor_table_company_2eproto_once, descriptor_table_company_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_company_2eproto::offsets,
    file_level_metadata_company_2eproto, file_level_enum_descriptors_company_2eproto,
    file_level_service_descriptors_company_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_company_2eproto_getter() {
  return &descriptor_table_company_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_company_2eproto(&descriptor_table_company_2eproto);

// ===================================================================

class company::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& open_date(const company* msg);
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& create_time(const company* msg);
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& update_time(const company* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
company::_Internal::open_date(const company* msg) {
  return *msg->_impl_.open_date_;
}
const ::PROTOBUF_NAMESPACE_ID::Timestamp&
company::_Internal::create_time(const company* msg) {
  return *msg->_impl_.create_time_;
}
const ::PROTOBUF_NAMESPACE_ID::Timestamp&
company::_Internal::update_time(const company* msg) {
  return *msg->_impl_.update_time_;
}
void company::clear_open_date() {
  if (GetArenaForAllocation() == nullptr && _impl_.open_date_ != nullptr) {
    delete _impl_.open_date_;
  }
  _impl_.open_date_ = nullptr;
}
void company::clear_create_time() {
  if (GetArenaForAllocation() == nullptr && _impl_.create_time_ != nullptr) {
    delete _impl_.create_time_;
  }
  _impl_.create_time_ = nullptr;
}
void company::clear_update_time() {
  if (GetArenaForAllocation() == nullptr && _impl_.update_time_ != nullptr) {
    delete _impl_.update_time_;
  }
  _impl_.update_time_ = nullptr;
}
company::company(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:company)
}
company::company(const company& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  company* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.address_){}
    , decltype(_impl_.open_date_){nullptr}
    , decltype(_impl_.create_time_){nullptr}
    , decltype(_impl_.update_time_){nullptr}
    , decltype(_impl_.id_){}
    , decltype(_impl_.last_year_income_){}
    , decltype(_impl_.employee_amount_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_address().empty()) {
    _this->_impl_.address_.Set(from._internal_address(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_open_date()) {
    _this->_impl_.open_date_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.open_date_);
  }
  if (from._internal_has_create_time()) {
    _this->_impl_.create_time_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.create_time_);
  }
  if (from._internal_has_update_time()) {
    _this->_impl_.update_time_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.update_time_);
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.employee_amount_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.employee_amount_));
  // @@protoc_insertion_point(copy_constructor:company)
}

inline void company::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.address_){}
    , decltype(_impl_.open_date_){nullptr}
    , decltype(_impl_.create_time_){nullptr}
    , decltype(_impl_.update_time_){nullptr}
    , decltype(_impl_.id_){uint64_t{0u}}
    , decltype(_impl_.last_year_income_){0}
    , decltype(_impl_.employee_amount_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

company::~company() {
  // @@protoc_insertion_point(destructor:company)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void company::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  _impl_.address_.Destroy();
  if (this != internal_default_instance()) delete _impl_.open_date_;
  if (this != internal_default_instance()) delete _impl_.create_time_;
  if (this != internal_default_instance()) delete _impl_.update_time_;
}

void company::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void company::Clear() {
// @@protoc_insertion_point(message_clear_start:company)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.address_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.open_date_ != nullptr) {
    delete _impl_.open_date_;
  }
  _impl_.open_date_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.create_time_ != nullptr) {
    delete _impl_.create_time_;
  }
  _impl_.create_time_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.update_time_ != nullptr) {
    delete _impl_.update_time_;
  }
  _impl_.update_time_ = nullptr;
  ::memset(&_impl_.id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.employee_amount_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.employee_amount_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* company::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "company.name"));
        } else
          goto handle_unusual;
        continue;
      // uint32 employee_amount = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.employee_amount_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string address = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "company.address"));
        } else
          goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp open_date = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_open_date(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double last_year_income = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _impl_.last_year_income_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp create_time = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_create_time(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp update_time = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_update_time(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* company::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:company)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_id(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "company.name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_name(), target);
  }

  // uint32 employee_amount = 3;
  if (this->_internal_employee_amount() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_employee_amount(), target);
  }

  // string address = 4;
  if (!this->_internal_address().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_address().data(), static_cast<int>(this->_internal_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "company.address");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_address(), target);
  }

  // .google.protobuf.Timestamp open_date = 5;
  if (this->_internal_has_open_date()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::open_date(this),
        _Internal::open_date(this).GetCachedSize(), target, stream);
  }

  // double last_year_income = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_last_year_income = this->_internal_last_year_income();
  uint64_t raw_last_year_income;
  memcpy(&raw_last_year_income, &tmp_last_year_income, sizeof(tmp_last_year_income));
  if (raw_last_year_income != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_last_year_income(), target);
  }

  // .google.protobuf.Timestamp create_time = 7;
  if (this->_internal_has_create_time()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::create_time(this),
        _Internal::create_time(this).GetCachedSize(), target, stream);
  }

  // .google.protobuf.Timestamp update_time = 8;
  if (this->_internal_has_update_time()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::update_time(this),
        _Internal::update_time(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:company)
  return target;
}

size_t company::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:company)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string address = 4;
  if (!this->_internal_address().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_address());
  }

  // .google.protobuf.Timestamp open_date = 5;
  if (this->_internal_has_open_date()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.open_date_);
  }

  // .google.protobuf.Timestamp create_time = 7;
  if (this->_internal_has_create_time()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.create_time_);
  }

  // .google.protobuf.Timestamp update_time = 8;
  if (this->_internal_has_update_time()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.update_time_);
  }

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_id());
  }

  // double last_year_income = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_last_year_income = this->_internal_last_year_income();
  uint64_t raw_last_year_income;
  memcpy(&raw_last_year_income, &tmp_last_year_income, sizeof(tmp_last_year_income));
  if (raw_last_year_income != 0) {
    total_size += 1 + 8;
  }

  // uint32 employee_amount = 3;
  if (this->_internal_employee_amount() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_employee_amount());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData company::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    company::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*company::GetClassData() const { return &_class_data_; }


void company::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<company*>(&to_msg);
  auto& from = static_cast<const company&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:company)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_address().empty()) {
    _this->_internal_set_address(from._internal_address());
  }
  if (from._internal_has_open_date()) {
    _this->_internal_mutable_open_date()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_open_date());
  }
  if (from._internal_has_create_time()) {
    _this->_internal_mutable_create_time()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_create_time());
  }
  if (from._internal_has_update_time()) {
    _this->_internal_mutable_update_time()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_update_time());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_last_year_income = from._internal_last_year_income();
  uint64_t raw_last_year_income;
  memcpy(&raw_last_year_income, &tmp_last_year_income, sizeof(tmp_last_year_income));
  if (raw_last_year_income != 0) {
    _this->_internal_set_last_year_income(from._internal_last_year_income());
  }
  if (from._internal_employee_amount() != 0) {
    _this->_internal_set_employee_amount(from._internal_employee_amount());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void company::CopyFrom(const company& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:company)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool company::IsInitialized() const {
  return true;
}

void company::InternalSwap(company* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.address_, lhs_arena,
      &other->_impl_.address_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(company, _impl_.employee_amount_)
      + sizeof(company::_impl_.employee_amount_)
      - PROTOBUF_FIELD_OFFSET(company, _impl_.open_date_)>(
          reinterpret_cast<char*>(&_impl_.open_date_),
          reinterpret_cast<char*>(&other->_impl_.open_date_));
}

::PROTOBUF_NAMESPACE_ID::Metadata company::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_company_2eproto_getter, &descriptor_table_company_2eproto_once,
      file_level_metadata_company_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::company*
Arena::CreateMaybeMessage< ::company >(Arena* arena) {
  return Arena::CreateMessageInternal< ::company >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
