// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_employee_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_employee_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_employee_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_employee_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_employee_2eproto;
class employee;
struct employeeDefaultTypeInternal;
extern employeeDefaultTypeInternal _employee_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::employee* Arena::CreateMaybeMessage<::employee>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class employee final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:employee) */ {
 public:
  inline employee() : employee(nullptr) {}
  ~employee() override;
  explicit PROTOBUF_CONSTEXPR employee(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  employee(const employee& from);
  employee(employee&& from) noexcept
    : employee() {
    *this = ::std::move(from);
  }

  inline employee& operator=(const employee& from) {
    CopyFrom(from);
    return *this;
  }
  inline employee& operator=(employee&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const employee& default_instance() {
    return *internal_default_instance();
  }
  static inline const employee* internal_default_instance() {
    return reinterpret_cast<const employee*>(
               &_employee_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(employee& a, employee& b) {
    a.Swap(&b);
  }
  inline void Swap(employee* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(employee* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  employee* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<employee>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const employee& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const employee& from) {
    employee::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(employee* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "employee";
  }
  protected:
  explicit employee(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 3,
    kAddressFieldNumber = 4,
    kIdFieldNumber = 1,
    kCompanyIdFieldNumber = 2,
    kIsEnrolledFieldNumber = 5,
  };
  // string name = 3;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string address = 4;
  void clear_address();
  const std::string& address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_address();
  PROTOBUF_NODISCARD std::string* release_address();
  void set_allocated_address(std::string* address);
  private:
  const std::string& _internal_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_address(const std::string& value);
  std::string* _internal_mutable_address();
  public:

  // int64 id = 1;
  void clear_id();
  int64_t id() const;
  void set_id(int64_t value);
  private:
  int64_t _internal_id() const;
  void _internal_set_id(int64_t value);
  public:

  // uint64 company_id = 2;
  void clear_company_id();
  uint64_t company_id() const;
  void set_company_id(uint64_t value);
  private:
  uint64_t _internal_company_id() const;
  void _internal_set_company_id(uint64_t value);
  public:

  // bool is_enrolled = 5;
  void clear_is_enrolled();
  bool is_enrolled() const;
  void set_is_enrolled(bool value);
  private:
  bool _internal_is_enrolled() const;
  void _internal_set_is_enrolled(bool value);
  public:

  // @@protoc_insertion_point(class_scope:employee)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr address_;
    int64_t id_;
    uint64_t company_id_;
    bool is_enrolled_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_employee_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// employee

// int64 id = 1;
inline void employee::clear_id() {
  _impl_.id_ = int64_t{0};
}
inline int64_t employee::_internal_id() const {
  return _impl_.id_;
}
inline int64_t employee::id() const {
  // @@protoc_insertion_point(field_get:employee.id)
  return _internal_id();
}
inline void employee::_internal_set_id(int64_t value) {
  
  _impl_.id_ = value;
}
inline void employee::set_id(int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:employee.id)
}

// uint64 company_id = 2;
inline void employee::clear_company_id() {
  _impl_.company_id_ = uint64_t{0u};
}
inline uint64_t employee::_internal_company_id() const {
  return _impl_.company_id_;
}
inline uint64_t employee::company_id() const {
  // @@protoc_insertion_point(field_get:employee.company_id)
  return _internal_company_id();
}
inline void employee::_internal_set_company_id(uint64_t value) {
  
  _impl_.company_id_ = value;
}
inline void employee::set_company_id(uint64_t value) {
  _internal_set_company_id(value);
  // @@protoc_insertion_point(field_set:employee.company_id)
}

// string name = 3;
inline void employee::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& employee::name() const {
  // @@protoc_insertion_point(field_get:employee.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void employee::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:employee.name)
}
inline std::string* employee::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:employee.name)
  return _s;
}
inline const std::string& employee::_internal_name() const {
  return _impl_.name_.Get();
}
inline void employee::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* employee::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* employee::release_name() {
  // @@protoc_insertion_point(field_release:employee.name)
  return _impl_.name_.Release();
}
inline void employee::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:employee.name)
}

// string address = 4;
inline void employee::clear_address() {
  _impl_.address_.ClearToEmpty();
}
inline const std::string& employee::address() const {
  // @@protoc_insertion_point(field_get:employee.address)
  return _internal_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void employee::set_address(ArgT0&& arg0, ArgT... args) {
 
 _impl_.address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:employee.address)
}
inline std::string* employee::mutable_address() {
  std::string* _s = _internal_mutable_address();
  // @@protoc_insertion_point(field_mutable:employee.address)
  return _s;
}
inline const std::string& employee::_internal_address() const {
  return _impl_.address_.Get();
}
inline void employee::_internal_set_address(const std::string& value) {
  
  _impl_.address_.Set(value, GetArenaForAllocation());
}
inline std::string* employee::_internal_mutable_address() {
  
  return _impl_.address_.Mutable(GetArenaForAllocation());
}
inline std::string* employee::release_address() {
  // @@protoc_insertion_point(field_release:employee.address)
  return _impl_.address_.Release();
}
inline void employee::set_allocated_address(std::string* address) {
  if (address != nullptr) {
    
  } else {
    
  }
  _impl_.address_.SetAllocated(address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.address_.IsDefault()) {
    _impl_.address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:employee.address)
}

// bool is_enrolled = 5;
inline void employee::clear_is_enrolled() {
  _impl_.is_enrolled_ = false;
}
inline bool employee::_internal_is_enrolled() const {
  return _impl_.is_enrolled_;
}
inline bool employee::is_enrolled() const {
  // @@protoc_insertion_point(field_get:employee.is_enrolled)
  return _internal_is_enrolled();
}
inline void employee::_internal_set_is_enrolled(bool value) {
  
  _impl_.is_enrolled_ = value;
}
inline void employee::set_is_enrolled(bool value) {
  _internal_set_is_enrolled(value);
  // @@protoc_insertion_point(field_set:employee.is_enrolled)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_employee_2eproto
